blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="blog/index.html")),
    url(r'^works/', TemplateView.as_view(template_name="blog/works.html")),
    url(r'^contact/', TemplateView.as_view(template_name="blog/contact.html")),
    url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    url(r'^blog/(?P<slug>[^\.]+)/$', views.PostView.as_view(), name='post')
]

portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^admin/', include(admin.site.urls)),
]

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    created_on = models.DateTimeField('date published')
    category = models.ForeignKey('blog.Category')


    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
        	self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('view_blog_post', (),
        	{
        		'slug' :self.slug,
        	})

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('view_blog_category', (),
            {
                'slug' :self.slug,
            })


# class Comment(models.Model):
#     name = models.CharField(max_length=42)
#     email = models.EmailField(max_length=75)
#     text = models.TextField()
#     post = models.ForeignKey(Post)
#     created_on = models.DateTimeField(auto_now_add=True)\

#     def __unicode__(self):
#         return self.text
    

    
    	

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Post, Category

class BlogView(generic.ListView):
    template_name = 'blog/blog.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        return Post.objects.order_by('-created_on')[:6]

class PostView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

blog/templates/blog/base.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>kc webdev</title>
    <link href='http://fonts.googleapis.com/css?family=Monda:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static "blog/img/favicon.ico"%}">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static "blog/js/script.js" %}"></script>
    <script id="shader-fs" type="x-shader/x-fragment">
        precision mediump float;
        varying vec4 vColor;
        void main(void) {
            gl_FragColor = vColor;
        }
    </script>

    <script id="shader-vs" type="x-shader/x-vertex">
        attribute vec3 aVertexPosition;
        attribute vec4 aVertexColor;
        uniform mat4 uMVMatrix;
        uniform mat4 uPMatrix;
        varying vec4 vColor;
        void main(void) {
            gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);
            vColor = aVertexColor;
        }
    </script>
    <script src="{% static "blog/js/3d.js" %}"></script>
    <script src="{% static "blog/js/webgl-utils.js" %}"></script>
    <script src="{% static "blog/js/triangle.js" %}"></script>
</head>
<body onload="webGLStart();">
<div id="menu-responsive">
    <a href="#"><img src="{% static "blog/img/respomenu.png" %}" alt=""></a>
    <ul>
        <li><a href="/">HOME</a></li>
        <li><a href="/works">WORKS</a></li>
        <li><a href="/contact">CONTACT</a></li>
        <li><a href="/blog">blog</a></li>
    </ul>
</div>
    <div id="header">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                    <ul>
                        <li><a href="/">HOME</a></li>
                        <li><a href="/works">WORKS</a></li>
                        <li><a href="/contact">CONTACT</a></li>
                        <li><a href="/blog">blog</a></li>
                    </ul>
                </div>
                </div>
            </div>
            <div class="clearfix"></div>
    </div>
{% block content %}   

{% endblock %}
    <div id="footer">
        <div class="container">
            <canvas id="pyramid"></canvas>
            <p>Konrad Chrzanowski &copy 2015</p>
        </div>
    </div>
</body>
</html>

blog/templates/blog/blog.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="content blog">
<div class="container">
<h1>Blog</h1>

{% if latest_post_list %}
    {% for post in latest_post_list %}
        <div class="post">
        <div class="row">
            <div class="twelve columns"> <h1>{{ post.title }}</h1> </div>
        </div>
        <div class="row">
            <div class="twelve columns">
                <p>{{ post.text|truncatechars:450 }}</p>
            </div>
        </div>
        
        
        <a href="{% url 'blog:post' post.slug %}">Read more</a>
        <div class="clearfix"></div>
        </div>
    {% endfor %}
{% endif %}

</div>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block content %}
<div id="contact" class="content">
    <div class="container">
    <h1>Contact</h1>
        <div class="row">
            <div class="twelve columns">
                <p>chrz.konrad@gmail.com</p>            
            </div>
        </div>
    
    </div>
    <div class="clearfix"></div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}
    <div id="about" class="content">
        <div class="container">
            <h1>About</h1>
            <div class="row">
                <div class="six columns">
                    <img src="{% static "blog/img/kon2.jpg" %}" alt="">
                </div>

                <div class="six columns">
                    <p>My name is Konrad Chrzanowski, and I am a student living in Łódź, Poland looking for a Front-End Developer position. </p><p>I have experience with HTML, CSS (Bootstrap, SCSS), JavaScript (AngularJS, jQuery, Ajax), C# and SQL, as well as Django and RubyOnRails skills.</p> <p>I am also familiar with PHP, Responsive Design, Git version control, and Gulp/Grunt, and plan on learning ReactJS and other native JavaScript tools. Check out my blog!</p>
                </div>
            </div>
            <div class="row">
                <div class="twelve columns">
                    <blockquote>“I am so clever that sometimes I don't understand a single word of what I am saying.”
                    <span>Oscar Wilde</span>
                    </blockquote> 
                </div>

            </div>
            <div class="row">
                <div class="twelve columns">
                    <div class="center">
                        <a href="#" id="cv">my cv</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="content blog post-full">
<div class="container">
    <div class="post">
        <div class="row">
            <div class="twelve columns"> <h1 class="title">{{ post.title }}</h1> </div>
        </div>
        <div class="row">
            <div class="twelve columns">
                <p>{{ post.text}}</p>
            </div>
        </div>
<a href="{% url 'blog:blog' %}">Back</a>
<div class="clearfix"></div>
</div>
</div>
</div>
{% endblock %}

blog/templates/blog/works.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block content %}
    <div id="works" class="content">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                <h1>Works</h1>
                </div>
            </div>
            <div class="row">
                <div class="four columns">
                    <div class="work">
                        <a href="#">
                        <span>This very website!</span>
                        <img src="{% static 'blog/img/com.jpg' %}" alt="">
                       
                        </a>
                    </div>     
                </div>
                <div class="four columns">
                    <div class="work">
                        <a href="http://manticore.uni.lodz.pl/~kchrzanows">
                        <span>Soul Asylum Records</span>
                        <img src="{% static 'blog/img/soul.jpg' %}" alt="">
                        
                        </a>
                        <p>Work In Progress!</p>
                    </div>     
                </div>
                <div class="four columns">
                    <div class="work">
                        <a href="http://www.langbay.eu">
                        <span>Langbay.eu</span>
                        <img src="{% static 'blog/img/lb.jpg' %}" alt="">
                        
                        </a>
                    </div>     
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}